- hosts: 35.246.230.2
  user: ubuntu
  become: true

  tasks:
    - name: Install JAVA related Ubuntu packages
      apt:
        name: "{{ packages }}"
        state: latest
      vars:
        packages:
          - default-jdk
