version: 2
jobs:
  init_and_plan:
    docker:
      - image: shakurit0/docker-for-tf-with-gcloud
    steps:
     - checkout
     - setup_remote_docker
     - run:
         name: init plugins and build infrastructure
         command: |
           echo $GOOGLE_CRED > terraform/credentials.json
           export GOOGLE_APPLICATION_CREDENTIALS="/root/project/terraform/credentials.json"
           cd terraform/
           terraform init
           terraform plan
  deploy:
    docker:
      - image: shakurit0/docker-for-tf-with-gcloud
    steps:
     - checkout
     - setup_remote_docker
     - run:
         name: simple deployment
         command: |
            echo "$GOOGLE_CRED" > gcloud-service-key.json
            gcloud auth activate-service-account $SERVICE_ACCOUNT --key-file=/root/project/gcloud-service-key.json --project=$PROJECT
            cd terraform/
            terraform init
            terraform apply -auto-approve
workflows:
  version: 2
  build_push_and_deploy:
    jobs:
      - init_and_plan:
         context:
           - flask
      - hold:
          type: approval
          requires:
           - init_and_plan 
      - deploy:
         context:
           - flask
         requires:
           - init_and_plan
           - hold
